language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpcs --standard=PSR2 bin/ src/
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry vendor/bin/coveralls
